### ISSUE TITLE
amqp_ssl_socket_new fails on raspberry pi 3 ?

### ISSUE THREAD

**Issue by petersilva** [alanxz/rabbitmq-c#620]
code:

cat >/tmp/kk.c <<EOT

#include <stdio.h>
#include <amqp.h>
#include <amqp_ssl_socket.h>

int main(int argc, char* argv[])
{

  amqp_connection_state_t conn;
  amqp_socket_t *socket;
  signed int status;

  conn = amqp_new_connection();
  socket =  amqp_ssl_socket_new(conn);

  if ( !socket ) {
     fprintf( stderr, "failed to get context\n" );
     return(1);
  }

}
EOT

pi@bwqd: $ cc -o kk kk.c -lrabbitmq
pi@bwqd: $ ./kk
failed to get context

The same code runs without error on amd64.   

pi@bwqd: $ uname -a
Linux bwqd 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
pi@bwqd: $

pi@bwqd: $ dpkg -l | grep rabbitmq
ii  librabbitmq-dev:armhf                 0.9.0-0.2                              armhf        AMQP client library written in C - Dev Files
ii  librabbitmq4:armhf                    0.9.0-0.2                              armhf        AMQP client library written in C
ii  rabbitmq-server                       3.7.8-4                                all          AMQP server written in Erlang
pi@bwqd: $ 

this is on debian buster.

armv7l is 32-bit.

**Comment by petersilva** [comment]
This does not happen with a git clone of the repository using the example amqp_ssl_connect.c so it has something to do with compiler options. but no idea what.  everything is buried deeply in cmake,

**Comment by petersilva** [comment]
other test points:  fails on ubuntu 20.04 64-bit on the rpi3 also.  but is fine on the rpi4.

**Comment by alanxz** [comment]
> This does not happen with a git clone of the repository using the example amqp_ssl_connect.c so it has something to do with compiler options. but no idea what

Do you mean that it fails with the prepackaged version on Ubuntu 20.02, but with what's in the master branch here?

There was a bug in v0.9.0 around initializing OpenSSL that was fixed in the master branch, alanxz/rabbitmq-c#523. It is included as a part of v.0.10.

**Comment by tmedicci** [comment]
Just an observation regarding #523: I've found that on OpenWrt (19.07.3 based), the error was still persistent in v0.10.0 to create the socket. #603 fixed it ;)

**Comment by alanxz** [comment]
@tmedicci good catch. #603 is the fix, its not yet in a tagged release (I was incorrect about it being included in v0.10.0).

**Comment by petersilva** [comment]
just to say that I built my app against the default branch at this git repo, and the problem is indeed gone.
